#seeing the world
location =['C', 'B', 'A', 'E','D']
print("원본출력:\n")
print(location)
print("sorted 출력:\n")
print(sorted(location))
print("원본출력:\n")
print(location)
print("reverse출력:\n")
location.reverse()
print(location)
print("다시 reverse출력:\n")
location.reverse()
print(location)
print("sort후 출력:\n")
location.sort()
print(location)
print("sort=reverse후 출력:\n")
location.sort(reverse=True)
print(location)